# Generated by Django 3.1.2 on 2020-10-30 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gasoline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('link_evidence', models.CharField(max_length=255)),
                ('type_complaint', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Datetime when the complaint is created')),
                ('offered_price', models.FloatField(help_text='Price published in the station', max_length=5)),
                ('actual_price', models.ForeignKey(help_text='Price registered in the system when creating the complaint', on_delete=django.db.models.deletion.CASCADE, to='gasoline.price')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasoline.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
