# Generated by Django 3.1.2 on 2020-10-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasoline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='status',
            field=models.CharField(default='ghost', max_length=10),
        ),
    ]
