# Generated by Django 3.1.2 on 2020-10-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasoline', '0004_auto_20201024_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date Time on wich the prices are registred', verbose_name='created at'),
        ),
    ]
