# Generated by Django 3.1.2 on 2020-10-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasoline', '0005_auto_20201024_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
