# Generated by Django 3.1.2 on 2020-10-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasoline', '0006_auto_20201024_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='gas_type',
            field=models.CharField(choices=[('premium', 'premium'), ('regular', 'regular'), ('diesel ', 'diesel')], help_text='Type of gasoline between the GAS_CHOICES', max_length=20),
        ),
    ]
